### ISSUE TITLE
bug: screenreader flag is ignored when sappy boxes, and checked regarding iOS readouts.

### ISSUE THREAD

**Issue by marrie** [talking-flight-monitor/talking-flight-monitor#150] opened 2022-08-28 22:18 UTC
**Describe the bug**
when reading the headings; of the ILS via screen reader if tfm is restarted (see below) the numbers read as 4.2, 4.1, 4.4 etc.

**To Reproduce**

1. launch tfm
2. set up for an ILS landing.
3. turn on appr mode when it's time to do so.
4. notice at first tfm reads in the sapi voice. [example here](https://user-images.githubusercontent.com/3614487/187096505-8128eb83-08cd-40d4-8236-80ff2b332b64.mp4)
5. restart tfm via tfm then control shift X.
6. this is when the screen reader option works, except this time, the headings for the glide will read as decimals, 4.1, 4.2, etc. [example here](https://user-images.githubusercontent.com/3614487/187096602-56bf3b97-ddba-4fbb-90ea-d395cadffc1c.mp4)
7. when you intercept the glide, the decimals will still read, [example here](https://user-images.githubusercontent.com/3614487/187096664-fa02613a-5ab6-4368-960d-5408f269a63a.mp4)

**Expected behavior**
I expected the screen reader (NVDA in my case) to read the headings as the sapi voice does.

**additional information
 - OS: [e.g. Windows 10]Windows 11 21H2 (x64) build 22000.918
 - TFM version: tfm-preview-22.9.1
 - Flight simulator in use: prepar3dv4.5 hf latest as of 2021
- specific aircraft in use: pmdg 737-800 ngxu

**Additional context**
n/a

**Comment by ajborka** [comment] 2022-08-29 21:23
Found the problem and the fix will be out with the next preview release. The decimal numbers you hear with NVDA are trim values.

**Comment by marrie** [comment] 2022-08-29 22:59
I NEED TO REDO THE FLIGHT TO TEST SOMETHING ELSE. The headings were not being read even with the screen reader after a restart of tfm, even the sapi was silenced yesterday. I believe we are on the right track however. Give me about 24 hours to try something else out.

 

Thanks.

**Comment by marrie** [comment] 2022-08-30 02:58
Ok, I did some further testing, and no heading were read out when I restarted tfm and   turned off the trim setting. I di dhear apptoatch off etc  however no headings were read by the screen reader. I ddid get the nav one has loc etc sapi read the headings when I turned on appr mode, when I restarted tfm, disabled trim reading, and listened, no headings were read. Video for what ever reason was not captured during this phase, only my landing.

**Comment by ajborka** [comment] 2022-08-30 04:35
That's OK... I ran a test and the problem is fixed. Will be in the next preview.

**Comment by marrie** [comment] 2022-08-30 04:52
Coolio! Thanks for this! I’ll be sure to brake, I mean play with this  next preview.

**Comment by ajborka** [comment] 2023-02-07 18:52
Fixed in previous previews.

**Closed by ajborka** 2023-02-07 18:52 UTC
