### ISSUE TITLE
Enhancement: Enable accessing the secondary CDU of PMDG aircraft through TFM for shared cockpit flying

### ISSUE THREAD

**Issue by robin24** [talking-flight-monitor/talking-flight-monitor#169] opened 2023-07-07 16:17 UTC
As was recently mentioned in the WhatsApp group, it is finally possible to perform shared cockpit flights using PMDG aircraft in MSFS thanks to the YourControls add-on.
Given this new development, it would be incredibly useful if the secondary / right CDU could be accessed through TFM, so that 2 pilots can work with the FMC without causing a conflict.
This possibility was briefly discussed in chat a long time ago, back then it was deemed as not being a priority because doing a shared cockpit session was not possible at the time, and there were concerns around potentially creating conflicts with First Officer.
With FSFO Next, however, it is my understanding that as long as the Program CDU config option is disabled, First Officer's interaction with the CDU is very minimal thus greatly reducing the likelihood of any potential conflicts.

My enhancement suggestion would thus be to implement access to the secondary CDU in TFM, and perhaps map it to CTRL-Shift-C or similar as the shortcut to bring it up.

**Comment by ajborka** [comment] 2023-07-07 16:37
Duplicate of #168 .

**Closed by ajborka** 2023-07-07 16:37 UTC
Labels: duplicate
