### ISSUE TITLE
bug: ILS Readings in latest preview not useable 

### ISSUE THREAD

**Issue by MarshallF03** [talking-flight-monitor/talking-flight-monitor#155] opened 2022-11-25 17:55 UTC
P3DV4.5HF3, PMDG737-700. ILS Runway 27 at EGNX east midlands. TFM Preview is called TFM 22.12 alpha 1. The ILS readings I was hearing were incorrect and did not catch up even when approach went off. I was only able to land because I've flown in here many times with it being my home airport. According to TFM when ever I was at say 2000FT waiting for the ILS to come in it would say the ILS was above me even at the point I would expect it to be just about ready to intersept. 
Please change the ILS reading system back to how it is in the current release edition of TFM. 
Dropbox link to audio file: https://www.dropbox.com/s/r6yn6c92d94opdz/landing%20ils27.mp3?dl=0

**Comment by ajborka** [comment] 2022-11-25 18:52
You don’t have to be centered on a glide slope to catch it. The requirement is at least 2.5degrees either side of the published slope. Catching it at 1700 feet below published altitude doesn’t seem too far off. The old way of reading ILS readouts is useless at best. If you want to turn it back on, uncheck the boxes for reading altitude in glide slope readouts and reading heading in localizer readouts.

**Comment by MarshallF03** [comment] 2022-11-25 21:02
Did you actually listen to the provided audio file? The issue here is that your readings were saying 1700 up when the approach light went off, which is not how it was in the release version of TFM when you have the new stuff on. Normally it is within hundreds of feet if that. I don’t understand why it did this. Only reason we were able to land was because I’ve done this approach many time before so knew how to force it to go

**Comment by ajborka** [comment] 2022-11-25 22:34
Still leaving this closed. There was no work on the ILS between its release in May and the 22.11 preview build. I did listen to the audio and everything looks normal. Sometimes you will catch the ILS at different points. I never capture it at the exact same location more than once. Sometimes I will miss it and require a go around or missed approach. So, unless you can give convincing proof that it is broken in 22.11 preview, the issue stays closed.

**Comment by MarshallF03** [comment] 2022-11-26 18:09
Hi Andy. 
I think I’ve found what you were asking for. 
So I ran the same approach in to EGNX with the following editions of TFM in the following order, going missed rather than landing.
Latest TFM Stable release, TFM Official Preview from the TFM Website, and the unofficial TFM 22.12 preview.
The issue I am referencing only happens in the unofficial preview which is the last clip in the audio file provided.
The clips are in the same order as what I mentioned the versions were at the top of this email.
The runway is the same, the aircraft is the same, the flight is the same.
Hope this helps
Thanks
Marshall
 
https://www.dropbox.com/s/4uwqhbnqzz9kqip/TFM%20ILS%20test.mp3?dl=0

**Comment by ajborka** [comment] 2022-11-26 18:47
There isn't an unofficial 22.12 preview unless you got it from someone else. Other people may compile source copies of TFM, and they may or may not work. Only trust official releases and official preview builds found on the website. Only those builds downloadable dirctly from the website are supported. Technically, the preview doesn't get any support other than bugs submitted in the repo.

**Comment by ajborka** [comment] 2022-11-28 16:05
This is confirmed when outside the United States. When going into RPLL, and 20nm from the airport, the ILS told me that it was 8000ft above me.

**Comment by MarshallF03** [comment] 2022-12-15 22:08
Hi, so I just completed a flight with thenew TFM preview in P3D with the 777. Had the exact same ILS issue. the readings were saying 15000 feet up by the time we got on the ground. Can you please look at this? 
https://www.dropbox.com/s/fbnc18ri68jzejj/TFM%20still%20has%20ILS%20issues.mp3?dl=0
Something has clearly changed between the may release and now. I have no idea what but it is not practical. I have had to remove the preview since I don’t fly in 2020 and the readings are unreliable.

**Comment by ajborka** [comment] 2022-12-15 22:50
We havent changed the ILS code since it was implemented in 22.5. I have seen a few other people with the same problem, and their Nagigraph data was out of date. Make sure you have the current cycle and try again. If that fails, give us the origin/destination airports to try.

**Comment by ajborka** [comment] 2022-12-15 22:56
Also try flying from KJFK to KBOS and let me know the results. Just flew it yesterday and had a final GS readout of 70 up at 100ft altitude.

**Comment by MarshallF03** [comment] 2022-12-15 23:19
So the flight was from EGLL to RCTP. I believe the navdata is all correct I’ll have to check again tomorrow

**Comment by ajborka** [comment] 2022-12-15 23:27
Will try it. Are you using SAPI or your screen reader for ILS readouts?

**Comment by MarshallF03** [comment] 2022-12-16 00:01
Using sappi


Sent from my iPod

On 15 Dec 2022, at 23:27, Andy Borka ***@***.******@***.***>> wrote:


Will try it. Are you using SAPI or your screen reader for ILS readouts?

**Comment by blindflightsimmer** [comment] 2022-12-16 23:49
can confirm this. Attempting an approach into EPKK Poland runway 25, readings are 63000 up on the ils rendering the readings unusable. Using MSFS having set right bracket ctrl D up with correct runway, with database set and navdata ETC all up to date. Something in latest preeview as first time I'm personally having this after upgrading.

**Comment by ajborka** [comment] 2022-12-17 14:36
For those using MSFS, did you run makerunways after installing all of the world updates?

**Comment by blindflightsimmer** [comment] 2022-12-18 02:37
Yes. Tfm also read’s runways and taxiways correctly and is able to reposition. Only item impacted is ils. On 17 Dec 2022, at 14:36, Andy Borka ***@***.***> wrote:﻿
For those using MSFS, did you run makerunways after installing all of the world updates?

**Comment by ajborka** [comment] 2022-12-20 14:27
Set up a destination runway. Without changing it, jump to some other airports. Does the distance NM part of the destination runway change, or does it still tell you distances are not available?

**Comment by blindflightsimmer** [comment] 2022-12-20 15:09
Hi, just tried these steps and here are the results.Loaded up in the pmdg 737-800 in p3dv5 at EGNX airport.Set up runway 27 in the dialogue at right bracket ctrl D.Hit okayWent back to the right bracket ctrl D dialogueObserved a listed distance in the text box to the selected runway of about 200 feet and 0.04 milesUsed tfm’s right bracket ctrl G to move to a gate at KJFKHit right bracket ctrl D againFound that 27 was selected at EGNX and that the distance remained at 200 feet and 0.04 milesRe-selected EGNX runway 27 and hit okRelaunched right bracket ctrl D and found that now the distance had updated to about 3000 miles awaySo the result is that the distance updated only if I reselected the runway after repositioning  Sent from Mail for Windows From: Andy BorkaSent: 20 December 2022 14:27To: talking-flight-monitor/talking-flight-monitorCc: blindflightsimmer; CommentSubject: Re: [talking-flight-monitor/talking-flight-monitor] bug: ILS Readings in latest preview not useable (Issue #155) Set up a destination runway. Without changing it, jump to some other airports. Does the distance NM part of the destination runway change, or does it still tell you distances are not available?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by blindflightsimmer** [comment] 2022-12-20 15:43
As my last message appeared jumbled in with some code, reposting here in case you need.
Hi, just tried these steps and here are the results.
1. Loaded up in the pmdg 737-800 in p3dv5 at EGNX airport.
2. Set up runway 27 in the dialogue at right bracket ctrl D.
3. Hit okay
4. Went back to the right bracket ctrl D dialogue
5. Observed a listed distance in the text box to the selected runway of about 200 feet and 0.04 miles
6. Used tfm’s right bracket ctrl G to move to a gate at KJFK
7. Hit right bracket ctrl D again
8. Found that 27 was selected at EGNX and that the distance remained at 200 feet and 0.04 miles
9. Re-selected EGNX runway 27 and hit ok
10. Relaunched right bracket ctrl D and found that now the distance had updated to about 3000 miles away
So the result is that the distance updated only if I reselected the runway after repositioning

**Comment by ajborka** [comment] 2022-12-20 15:56
Here is your test with the potential fix:

1. Loaded up at EGNX/27.
2. Set destination runway to EGNX/27.
3. Whent into destination runway window and saw distance at 500.08FT/0.08NM.
4. Repositioned to KJFK/A1.
5. Whent into destination runway window and saw an updated distance of 2936.9NM
6. Repositioned to KLAX/Gate 201.
7. Whent into destination runway and saw an updated distance of 4652.9NM.

Let me know if this appears fixed before I push a hotfix.

**Comment by blindflightsimmer** [comment] 2022-12-20 16:06
All the distances are correct and since it auto-updated I'm guessing that will be good now.

**Comment by ajborka** [comment] 2022-12-20 16:07
The above is for MSFS database. The P3D database gave slightly different results. The main thing is that I didn't have to choose the runway in the destination runway window multiple times. Setting it only once before my jumps worked.

**Comment by blindflightsimmer** [comment] 2022-12-20 16:09
Exactly. Any discrepancies   in our distances are minor and probably down to using slightly differing sceneries for EGNX and KJFK, but as you say the difference now is that it auto-updates without having to be re-selected which is not currently the case on the released preview.

**Comment by ajborka** [comment] 2022-12-20 16:14
Pushing hotfix soon. Fixed with 546d39e

**Closed by ajborka** 2022-12-20 16:14 UTC
